gword = [{text: 'Iraq', size: 100},
{text: 'Pakistan', size: 73},
{text: 'Afghanistan', size: 69},
{text: 'India', size: 41},
{text: 'Nigeria', size: 35},
{text: 'Yemen', size: 34},
{text: 'Philippines', size: 34},
{text: 'Ukraine', size: 29},
{text: 'Somalia', size: 29},
{text: 'Thailand', size: 29},
{text: 'Libya', size: 28},
{text: 'Egypt', size: 28},
{text: 'Syria', size: 27},
{text: 'Bangladesh', size: 24},
{text: 'Turkey', size: 23},
{text: 'Colombia', size: 22},
{text: 'West Bank and Gaza Strip', size: 21},
{text: 'Israel', size: 21},
{text: 'Sudan', size: 21},
{text: 'United Kingdom', size: 21},
{text: 'Lebanon', size: 20},
{text: 'Russia', size: 20},
{text: 'Kenya', size: 20},
{text: 'Democratic Republic of the Congo', size: 20},
{text: 'Mali', size: 20}
];
